version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/contentful/gofog
    steps:
      - checkout
      - run:
          name: Installing dep
          command: |
            go get -d -u github.com/golang/dep/cmd/dep
            go install github.com/golang/dep/cmd/dep
      - run:
          name: Fetching dependencies
          command: dep ensure
      - run:
          name: Build binary
          command: go build
      - run:
          name: Generate checksum
          command: sha512sum gofog > gofog.sum
      - run:
          name: Fetch upload tools
          command: |
            sudo apt-get update
            sudo apt-get install awscli 
      - deploy:
          name: Upload to S3
          command: |
            if [[ "$CIRCLE_BRANCH" != "master" ]]; then exit 0; fi
            FILENAME=gofog
            if [[ "$CIRCLE_TAG" != "" ]]; then
              FILENAME="gofog-$CIRCLE_TAG"
            fi
            aws s3 cp ./gofog s3://${LAB_ASSETS_BUCKET}/${FILENAME} --acl public-read
            aws s3 cp ./gofog.sum s3://${LAB_ASSETS_BUCKET}/${FILENAME}.sum --acl public-read

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
